/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 scene.gltf 
Author: riach (https://sketchfab.com/riach)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/lipstick-3a22a4359df74375a297d962926f0359
Title: Lipstick
*/

import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";

export function Lipstick(props) {
  const { nodes, materials } = useGLTF("/models/lipstick/scene.gltf");

  return (
    <group {...props} dispose={null}>
      <group scale={0.025}>
        <mesh
          geometry={nodes["lipstick_holder_Material_#31_0"].geometry}
          material={materials.Material_31}
          position={[-129.371, -3.681, 10.691]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[1.343, 1.343, 1.396]}
        />
        <mesh
          geometry={nodes["lipstick_red_Material_#29_0"].geometry}
          material={materials.Material_29}
          position={[-129.339, 29.462, 10.662]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={1.084}
        />
        <mesh
          geometry={nodes["lipstick_cap_Material_#30_0"].geometry}
          material={materials.Material_30}
          position={[-129.577, -30.029, 49.369]}
          rotation={[-Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/models/lipstick/scene.gltf");
